version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/laps"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "maven"
    groups:
      maven-production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      maven-development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
