#!/usr/bin/env bash
# setup-nginx-https.sh — Idempotent nginx + self-signed TLS setup for LAPS on EC2
#
# Usage: bash setup-nginx-https.sh <DOMAIN>
#   DOMAIN — EC2 public DNS hostname (e.g. ec2-1-2-3-4.compute-1.amazonaws.com)
#
# Run on every deploy. The self-signed certificate is regenerated each time so
# it always matches the current EC2_HOST value (AWS Academy dynamic DNS — issue #9).
#
# Security controls implemented:
#   ASVS V9.1.1  — TLS 1.2/1.3 only, Mozilla Intermediate cipher suite
#   ASVS V9.1.3  — HSTS max-age=31536000; includeSubDomains
#   ASVS V6.4.1  — Private key chmod 600, owned by root
#   ASVS V14.4.3 — X-Frame-Options: SAMEORIGIN
#   ASVS V14.4.4 — X-Content-Type-Options: nosniff
#   ASVS V13.2.6 — X-Forwarded-Proto and X-Real-IP forwarded to Spring Boot

set -euo pipefail

DOMAIN="${1:?Usage: $0 <DOMAIN>}"
CERT_DIR="/opt/laps/ssl"
NGINX_CONF="/etc/nginx/conf.d/laps.conf"

# ---------------------------------------------------------------------------
# 1. Install nginx and openssl (dnf is idempotent — safe to re-run)
# ---------------------------------------------------------------------------
echo "[1/6] Installing nginx and openssl..."
sudo dnf install -y nginx openssl

# ---------------------------------------------------------------------------
# 2. Create cert directory with tight permissions
# ---------------------------------------------------------------------------
echo "[2/6] Creating certificate directory ${CERT_DIR}..."
sudo mkdir -p "${CERT_DIR}"
sudo chmod 700 "${CERT_DIR}"

# ---------------------------------------------------------------------------
# 3. Generate self-signed certificate (regenerated on every deploy so CN always
#    matches the current dynamic EC2 DNS hostname)
# ---------------------------------------------------------------------------
echo "[3/6] Generating self-signed certificate for ${DOMAIN}..."
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout "${CERT_DIR}/server.key" \
  -out    "${CERT_DIR}/server.crt" \
  -subj   "/CN=${DOMAIN}" \
  -addext "subjectAltName=DNS:${DOMAIN}"

# Private key must be readable by root only (ASVS V6.4.1)
sudo chmod 600 "${CERT_DIR}/server.key"
sudo chmod 644 "${CERT_DIR}/server.crt"

# ---------------------------------------------------------------------------
# 4. Write nginx configuration
# ---------------------------------------------------------------------------
echo "[4/6] Writing nginx configuration to ${NGINX_CONF}..."
sudo tee "${NGINX_CONF}" > /dev/null <<NGINX_CONFIG
# LAPS nginx reverse-proxy configuration (issue #9)
# Generated by setup-nginx-https.sh — do not edit manually.

# Redirect all plain HTTP to HTTPS (ASVS V9.1.1)
server {
    listen 80;
    server_name ${DOMAIN};

    # Return 301 for all requests
    return 301 https://\$host\$request_uri;
}

# TLS-terminating reverse proxy → Spring Boot on localhost:8080
server {
    listen 443 ssl;
    server_name ${DOMAIN};

    # Certificate paths
    ssl_certificate     ${CERT_DIR}/server.crt;
    ssl_certificate_key ${CERT_DIR}/server.key;

    # TLS protocol versions — disable TLS 1.0 and 1.1 (ASVS V9.1.1)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Mozilla Intermediate cipher suite (2023) — no RC4, no 3DES, no export ciphers
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # TLS session cache for performance
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # Security response headers
    # HSTS — tell browsers to only use HTTPS for 1 year (ASVS V9.1.3)
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    # Prevent clickjacking (ASVS V14.4.3)
    add_header X-Frame-Options SAMEORIGIN always;
    # Prevent MIME sniffing (ASVS V14.4.4)
    add_header X-Content-Type-Options nosniff always;

    # Proxy to Spring Boot (port 8080 must be localhost-only — see README)
    location / {
        proxy_pass         http://127.0.0.1:8080;
        proxy_http_version 1.1;

        # Forward client identity to Spring Boot (ASVS V13.2.6)
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
    }
}
NGINX_CONFIG

# ---------------------------------------------------------------------------
# 5. Validate nginx configuration before applying
# ---------------------------------------------------------------------------
echo "[5/6] Validating nginx configuration..."
sudo nginx -t

# ---------------------------------------------------------------------------
# 6. Enable and (re)start nginx
# ---------------------------------------------------------------------------
echo "[6/6] Enabling and reloading nginx..."
sudo systemctl enable nginx

if systemctl is-active --quiet nginx; then
    sudo systemctl reload nginx
else
    sudo systemctl start nginx
fi

echo ""
echo "nginx HTTPS setup complete."
echo "  Certificate : ${CERT_DIR}/server.crt  (self-signed, valid 365 days)"
echo "  Private key : ${CERT_DIR}/server.key  (chmod 600)"
echo "  Domain      : ${DOMAIN}"
echo ""
echo "NOTE: Browsers will show a self-signed certificate warning — this is expected."
echo "      Click Advanced -> Proceed to access the application."
echo ""
echo "Verify with:"
echo "  curl -k -I https://${DOMAIN}/login"
echo "  curl -I  http://${DOMAIN}   # should return 301"
